apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maps
  labels:
    name: maps
  namespace: apigee
spec:
  replicas: 1
  selector:
    matchLabels:
      component: maps
  template:
    metadata:
      labels:
        component: maps
        routable: "true"
      annotations:
        privateHosts: sso.k8s.local
        privatePaths: 3000:/maps
    spec:
      containers:
      - name: maps
        image: maps
        imagePullPolicy: IfNotPresent
        env:
          - name: PORT
            value: "3000"
          - name: PG_HOST
            valueFrom:
              secretKeyRef:
                name: maps
                key: pghost
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: maps
                key: pguser
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: maps
                key: pgpassword
          - name: PG_DATABASE
            valueFrom:
              secretKeyRef:
                name: maps
                key: pgdatabase
          - name: SHIPYARD_PRIVATE_SECRET
            valueFrom:
              secretKeyRef:
                name: routing
                key: private-api-key
          - name: SPEEDUP
            value: "10" 
          - name: INTERNAL_SY_ROUTER_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP          
          - name: INTERNAL_SY_ROUTER_PORT
            value: "30556"
          - name: IPADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP          
        ports:
          - containerPort: 3000